#include "types.idl"


module org # 1000
{
  module xtreemfs # 0
  {
    module babudb # 0
    {
      module interfaces # 0
      {
	interface ReplicationInterface # 10
	{
	  // Constants
	  const uint32_t DEFAULT_PORT = 35667;
	  const uint32_t DEFAULT_SPORT = 35667;

	  // Functions	
	  // shared
	  LSN state() # 1;				    // state request from master/slave 
	  DBFileMetaDataSet load (LSN lsn) # 2;             // load request from the master/slave
      	  buffer chunk (Chunk chunk) # 3;                   // chunk request from the master/slave
	  void flease(buffer message, string host, uint32_t port) # 4;                  // flease message from master/slave
	  uint64_t localTime() # 5;                         // time request from the master/slave
	  
	  // master
	  LogEntries replica (LSNRange range) # 6;	    // getReplica request from a slave
	  void heartbeat(LSN lsn) # 7;                      // heartbeat message from a slave

	  // slave
	  void replicate (LSN lsn, LogEntry logEntry) # 8;  // replicate request from the master

	  exception ProtocolException # 90 { uint32_t accept_stat; uint32_t error_code; string stack_trace; };
	  exception errnoException # 91 { uint32_t error_code; string error_message; string stack_trace; };
	};
      };
    };
  };
};
