// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: interface/RemoteAccess.proto

package org.xtreemfs.babudb.pbrpc;

public final class RemoteAccess {
  private RemoteAccess() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034interface/RemoteAccess.proto\022\022org.xtre" +
      "emfs.pbrpc\032\033interface/GlobalTypes.proto\032" +
      "%share/foundation/include/Common.proto\032$" +
      "share/foundation/include/PBRPC.proto2\335\006\n" +
      "\023RemoteAccessService\022]\n\016makePersistent\022 " +
      ".org.xtreemfs.pbrpc.emptyRequest\032\034.org.x" +
      "treemfs.pbrpc.Database\"\013\215\265\030\001\000\000\000\240\265\030\001\022\\\n\021g" +
      "etDatabaseByName\022 .org.xtreemfs.pbrpc.Da" +
      "tabaseName\032\034.org.xtreemfs.pbrpc.Database" +
      "\"\007\215\265\030\002\000\000\000\022X\n\017getDatabaseById\022\036.org.xtree",
      "mfs.pbrpc.DatabaseId\032\034.org.xtreemfs.pbrp" +
      "c.Database\"\007\215\265\030\003\000\000\000\022X\n\014getDatabases\022 .or" +
      "g.xtreemfs.pbrpc.emptyRequest\032\035.org.xtre" +
      "emfs.pbrpc.Databases\"\007\215\265\030\004\000\000\000\022\\\n\006lookup\022" +
      "\032.org.xtreemfs.pbrpc.Lookup\032%.org.xtreem" +
      "fs.pbrpc.ErrorCodeResponse\"\017\215\265\030\005\000\000\000\240\265\030\001\230" +
      "\265\030\001\022T\n\007plookup\022\032.org.xtreemfs.pbrpc.Look" +
      "up\032\034.org.xtreemfs.pbrpc.EntryMap\"\017\215\265\030\006\000\000" +
      "\000\240\265\030\001\230\265\030\001\022[\n\016plookupReverse\022\032.org.xtreem" +
      "fs.pbrpc.Lookup\032\034.org.xtreemfs.pbrpc.Ent",
      "ryMap\"\017\215\265\030\007\000\000\000\240\265\030\001\230\265\030\001\022Y\n\007rlookup\022\037.org." +
      "xtreemfs.pbrpc.RangeLookup\032\034.org.xtreemf" +
      "s.pbrpc.EntryMap\"\017\215\265\030\010\000\000\000\240\265\030\001\230\265\030\001\022`\n\016rlo" +
      "okupReverse\022\037.org.xtreemfs.pbrpc.RangeLo" +
      "okup\032\034.org.xtreemfs.pbrpc.EntryMap\"\017\215\265\030\t" +
      "\000\000\000\240\265\030\001\230\265\030\001\032\007\225\265\030\021\'\000\000B\033\n\031org.xtreemfs.bab" +
      "udb.pbrpc"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          com.google.protobuf.ExtensionRegistry registry =
            com.google.protobuf.ExtensionRegistry.newInstance();
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.procId);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.dataIn);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.procId);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.procId);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.procId);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.procId);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.dataOut);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.dataIn);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.procId);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.dataOut);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.dataIn);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.procId);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.dataOut);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.dataIn);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.procId);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.dataOut);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.dataIn);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.procId);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.dataOut);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.dataIn);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.interfaceId);
          return registry;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.xtreemfs.babudb.pbrpc.GlobalTypes.getDescriptor(),
          org.xtreemfs.babudb.pbrpc.Common.getDescriptor(),
          org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
