// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: interface/Replication.proto

package org.xtreemfs.babudb.pbrpc;

public final class Replication {
  private Replication() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033interface/Replication.proto\022\022org.xtree" +
      "mfs.pbrpc\032\033interface/GlobalTypes.proto\032%" +
      "share/foundation/include/Common.proto\032$s" +
      "hare/foundation/include/PBRPC.proto2\217\007\n\022" +
      "ReplicationService\022K\n\005state\022 .org.xtreem" +
      "fs.pbrpc.emptyRequest\032\027.org.xtreemfs.pbr" +
      "pc.LSN\"\007\215\265\030\001\000\000\000\022M\n\004load\022\027.org.xtreemfs.p" +
      "brpc.LSN\032#.org.xtreemfs.pbrpc.DBFileMeta" +
      "Datas\"\007\215\265\030\002\000\000\000\022V\n\005chunk\022\031.org.xtreemfs.p" +
      "brpc.Chunk\032%.org.xtreemfs.pbrpc.ErrorCod",
      "eResponse\"\013\215\265\030\003\000\000\000\230\265\030\001\022X\n\006flease\022\032.org.x" +
      "treemfs.pbrpc.FLease\032%.org.xtreemfs.pbrp" +
      "c.ErrorCodeResponse\"\013\215\265\030\004\000\000\000\240\265\030\001\022U\n\tloca" +
      "lTime\022 .org.xtreemfs.pbrpc.emptyRequest\032" +
      "\035.org.xtreemfs.pbrpc.Timestamp\"\007\215\265\030\005\000\000\000\022" +
      "T\n\007replica\022\034.org.xtreemfs.pbrpc.LSNRange" +
      "\032\036.org.xtreemfs.pbrpc.LogEntries\"\013\215\265\030\006\000\000" +
      "\000\230\265\030\001\022a\n\theartbeat\022$.org.xtreemfs.pbrpc." +
      "HeartbeatMessage\032%.org.xtreemfs.pbrpc.Er" +
      "rorCodeResponse\"\007\215\265\030\007\000\000\000\022X\n\treplicate\022\027.",
      "org.xtreemfs.pbrpc.LSN\032%.org.xtreemfs.pb" +
      "rpc.ErrorCodeResponse\"\013\215\265\030\010\000\000\000\240\265\030\001\022c\n\013sy" +
      "nchronize\022$.org.xtreemfs.pbrpc.Heartbeat" +
      "Message\032%.org.xtreemfs.pbrpc.ErrorCodeRe" +
      "sponse\"\007\215\265\030\t\000\000\000\022S\n\rvolatileState\022 .org.x" +
      "treemfs.pbrpc.emptyRequest\032\027.org.xtreemf" +
      "s.pbrpc.LSN\"\007\215\265\030\n\000\000\000\032\007\225\265\030!N\000\000B\033\n\031org.xtr" +
      "eemfs.babudb.pbrpc"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          com.google.protobuf.ExtensionRegistry registry =
            com.google.protobuf.ExtensionRegistry.newInstance();
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.procId);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.procId);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.procId);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.dataOut);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.procId);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.dataIn);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.procId);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.procId);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.dataOut);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.procId);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.procId);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.dataIn);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.procId);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.procId);
          registry.add(org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.interfaceId);
          return registry;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.xtreemfs.babudb.pbrpc.GlobalTypes.getDescriptor(),
          org.xtreemfs.babudb.pbrpc.Common.getDescriptor(),
          org.xtreemfs.babudb.pbrpc.generatedinterfaces.PBRPC.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
