// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: interface/replication.proto

package org.xtreemfs.babudb.pbrpc;

public final class Replication {
  private Replication() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static abstract class RemoteAccessService
      implements com.google.protobuf.Service {
    protected RemoteAccessService() {}
    
    public interface Interface {
      public abstract void makePersistent(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.Common.emptyRequest request,
          com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new RemoteAccessService() {
        @Override
        public  void makePersistent(
            com.google.protobuf.RpcController controller,
            org.xtreemfs.babudb.pbrpc.Common.emptyRequest request,
            com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done) {
          impl.makePersistent(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.makePersistent(controller, (org.xtreemfs.babudb.pbrpc.Common.emptyRequest)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.xtreemfs.babudb.pbrpc.Common.emptyRequest.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void makePersistent(
        com.google.protobuf.RpcController controller,
        org.xtreemfs.babudb.pbrpc.Common.emptyRequest request,
        com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.xtreemfs.babudb.pbrpc.Replication.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.makePersistent(controller, (org.xtreemfs.babudb.pbrpc.Common.emptyRequest)request,
            com.google.protobuf.RpcUtil.<org.xtreemfs.babudb.pbrpc.Common.emptyResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.xtreemfs.babudb.pbrpc.Common.emptyRequest.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends org.xtreemfs.babudb.pbrpc.Replication.RemoteAccessService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void makePersistent(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.Common.emptyRequest request,
          com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.xtreemfs.babudb.pbrpc.Common.emptyResponse.class,
            org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public org.xtreemfs.babudb.pbrpc.Common.emptyResponse makePersistent(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.Common.emptyRequest request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public org.xtreemfs.babudb.pbrpc.Common.emptyResponse makePersistent(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.Common.emptyRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.xtreemfs.babudb.pbrpc.Common.emptyResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance());
      }
      
    }
  }
  
  public static abstract class ReplicationService
      implements com.google.protobuf.Service {
    protected ReplicationService() {}
    
    public interface Interface {
      public abstract void state(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.Common.emptyRequest request,
          com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN> done);
      
      public abstract void load(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN request,
          com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.GlobalTypes.DBFileMetaDatas> done);
      
      public abstract void chunk(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.Chunk request,
          com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done);
      
      public abstract void flease(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.FLease request,
          com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done);
      
      public abstract void localTime(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.Common.emptyRequest request,
          com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.GlobalTypes.Timestamp> done);
      
      public abstract void replica(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LSNRange request,
          com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.GlobalTypes.LogEntries> done);
      
      public abstract void heartbeat(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN request,
          com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done);
      
      public abstract void replicate(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN request,
          com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done);
      
    }
    
    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new ReplicationService() {
        @Override
        public  void state(
            com.google.protobuf.RpcController controller,
            org.xtreemfs.babudb.pbrpc.Common.emptyRequest request,
            com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN> done) {
          impl.state(controller, request, done);
        }
        
        @Override
        public  void load(
            com.google.protobuf.RpcController controller,
            org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN request,
            com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.GlobalTypes.DBFileMetaDatas> done) {
          impl.load(controller, request, done);
        }
        
        @Override
        public  void chunk(
            com.google.protobuf.RpcController controller,
            org.xtreemfs.babudb.pbrpc.GlobalTypes.Chunk request,
            com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done) {
          impl.chunk(controller, request, done);
        }
        
        @Override
        public  void flease(
            com.google.protobuf.RpcController controller,
            org.xtreemfs.babudb.pbrpc.GlobalTypes.FLease request,
            com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done) {
          impl.flease(controller, request, done);
        }
        
        @Override
        public  void localTime(
            com.google.protobuf.RpcController controller,
            org.xtreemfs.babudb.pbrpc.Common.emptyRequest request,
            com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.GlobalTypes.Timestamp> done) {
          impl.localTime(controller, request, done);
        }
        
        @Override
        public  void replica(
            com.google.protobuf.RpcController controller,
            org.xtreemfs.babudb.pbrpc.GlobalTypes.LSNRange request,
            com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.GlobalTypes.LogEntries> done) {
          impl.replica(controller, request, done);
        }
        
        @Override
        public  void heartbeat(
            com.google.protobuf.RpcController controller,
            org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN request,
            com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done) {
          impl.heartbeat(controller, request, done);
        }
        
        @Override
        public  void replicate(
            com.google.protobuf.RpcController controller,
            org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN request,
            com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done) {
          impl.replicate(controller, request, done);
        }
        
      };
    }
    
    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        
        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.state(controller, (org.xtreemfs.babudb.pbrpc.Common.emptyRequest)request);
            case 1:
              return impl.load(controller, (org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN)request);
            case 2:
              return impl.chunk(controller, (org.xtreemfs.babudb.pbrpc.GlobalTypes.Chunk)request);
            case 3:
              return impl.flease(controller, (org.xtreemfs.babudb.pbrpc.GlobalTypes.FLease)request);
            case 4:
              return impl.localTime(controller, (org.xtreemfs.babudb.pbrpc.Common.emptyRequest)request);
            case 5:
              return impl.replica(controller, (org.xtreemfs.babudb.pbrpc.GlobalTypes.LSNRange)request);
            case 6:
              return impl.heartbeat(controller, (org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN)request);
            case 7:
              return impl.replicate(controller, (org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN)request);
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.xtreemfs.babudb.pbrpc.Common.emptyRequest.getDefaultInstance();
            case 1:
              return org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN.getDefaultInstance();
            case 2:
              return org.xtreemfs.babudb.pbrpc.GlobalTypes.Chunk.getDefaultInstance();
            case 3:
              return org.xtreemfs.babudb.pbrpc.GlobalTypes.FLease.getDefaultInstance();
            case 4:
              return org.xtreemfs.babudb.pbrpc.Common.emptyRequest.getDefaultInstance();
            case 5:
              return org.xtreemfs.babudb.pbrpc.GlobalTypes.LSNRange.getDefaultInstance();
            case 6:
              return org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN.getDefaultInstance();
            case 7:
              return org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN.getDefaultInstance();
            case 1:
              return org.xtreemfs.babudb.pbrpc.GlobalTypes.DBFileMetaDatas.getDefaultInstance();
            case 2:
              return org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance();
            case 3:
              return org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance();
            case 4:
              return org.xtreemfs.babudb.pbrpc.GlobalTypes.Timestamp.getDefaultInstance();
            case 5:
              return org.xtreemfs.babudb.pbrpc.GlobalTypes.LogEntries.getDefaultInstance();
            case 6:
              return org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance();
            case 7:
              return org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance();
            default:
              throw new java.lang.AssertionError("Can't get here.");
          }
        }
        
      };
    }
    
    public abstract void state(
        com.google.protobuf.RpcController controller,
        org.xtreemfs.babudb.pbrpc.Common.emptyRequest request,
        com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN> done);
    
    public abstract void load(
        com.google.protobuf.RpcController controller,
        org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN request,
        com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.GlobalTypes.DBFileMetaDatas> done);
    
    public abstract void chunk(
        com.google.protobuf.RpcController controller,
        org.xtreemfs.babudb.pbrpc.GlobalTypes.Chunk request,
        com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done);
    
    public abstract void flease(
        com.google.protobuf.RpcController controller,
        org.xtreemfs.babudb.pbrpc.GlobalTypes.FLease request,
        com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done);
    
    public abstract void localTime(
        com.google.protobuf.RpcController controller,
        org.xtreemfs.babudb.pbrpc.Common.emptyRequest request,
        com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.GlobalTypes.Timestamp> done);
    
    public abstract void replica(
        com.google.protobuf.RpcController controller,
        org.xtreemfs.babudb.pbrpc.GlobalTypes.LSNRange request,
        com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.GlobalTypes.LogEntries> done);
    
    public abstract void heartbeat(
        com.google.protobuf.RpcController controller,
        org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN request,
        com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done);
    
    public abstract void replicate(
        com.google.protobuf.RpcController controller,
        org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN request,
        com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done);
    
    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return org.xtreemfs.babudb.pbrpc.Replication.getDescriptor().getServices().get(1);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    
    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.state(controller, (org.xtreemfs.babudb.pbrpc.Common.emptyRequest)request,
            com.google.protobuf.RpcUtil.<org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN>specializeCallback(
              done));
          return;
        case 1:
          this.load(controller, (org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN)request,
            com.google.protobuf.RpcUtil.<org.xtreemfs.babudb.pbrpc.GlobalTypes.DBFileMetaDatas>specializeCallback(
              done));
          return;
        case 2:
          this.chunk(controller, (org.xtreemfs.babudb.pbrpc.GlobalTypes.Chunk)request,
            com.google.protobuf.RpcUtil.<org.xtreemfs.babudb.pbrpc.Common.emptyResponse>specializeCallback(
              done));
          return;
        case 3:
          this.flease(controller, (org.xtreemfs.babudb.pbrpc.GlobalTypes.FLease)request,
            com.google.protobuf.RpcUtil.<org.xtreemfs.babudb.pbrpc.Common.emptyResponse>specializeCallback(
              done));
          return;
        case 4:
          this.localTime(controller, (org.xtreemfs.babudb.pbrpc.Common.emptyRequest)request,
            com.google.protobuf.RpcUtil.<org.xtreemfs.babudb.pbrpc.GlobalTypes.Timestamp>specializeCallback(
              done));
          return;
        case 5:
          this.replica(controller, (org.xtreemfs.babudb.pbrpc.GlobalTypes.LSNRange)request,
            com.google.protobuf.RpcUtil.<org.xtreemfs.babudb.pbrpc.GlobalTypes.LogEntries>specializeCallback(
              done));
          return;
        case 6:
          this.heartbeat(controller, (org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN)request,
            com.google.protobuf.RpcUtil.<org.xtreemfs.babudb.pbrpc.Common.emptyResponse>specializeCallback(
              done));
          return;
        case 7:
          this.replicate(controller, (org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN)request,
            com.google.protobuf.RpcUtil.<org.xtreemfs.babudb.pbrpc.Common.emptyResponse>specializeCallback(
              done));
          return;
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.xtreemfs.babudb.pbrpc.Common.emptyRequest.getDefaultInstance();
        case 1:
          return org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN.getDefaultInstance();
        case 2:
          return org.xtreemfs.babudb.pbrpc.GlobalTypes.Chunk.getDefaultInstance();
        case 3:
          return org.xtreemfs.babudb.pbrpc.GlobalTypes.FLease.getDefaultInstance();
        case 4:
          return org.xtreemfs.babudb.pbrpc.Common.emptyRequest.getDefaultInstance();
        case 5:
          return org.xtreemfs.babudb.pbrpc.GlobalTypes.LSNRange.getDefaultInstance();
        case 6:
          return org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN.getDefaultInstance();
        case 7:
          return org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN.getDefaultInstance();
        case 1:
          return org.xtreemfs.babudb.pbrpc.GlobalTypes.DBFileMetaDatas.getDefaultInstance();
        case 2:
          return org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance();
        case 3:
          return org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance();
        case 4:
          return org.xtreemfs.babudb.pbrpc.GlobalTypes.Timestamp.getDefaultInstance();
        case 5:
          return org.xtreemfs.babudb.pbrpc.GlobalTypes.LogEntries.getDefaultInstance();
        case 6:
          return org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance();
        case 7:
          return org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance();
        default:
          throw new java.lang.AssertionError("Can't get here.");
      }
    }
    
    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }
    
    public static final class Stub extends org.xtreemfs.babudb.pbrpc.Replication.ReplicationService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.RpcChannel channel;
      
      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }
      
      public  void state(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.Common.emptyRequest request,
          com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN.class,
            org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN.getDefaultInstance()));
      }
      
      public  void load(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN request,
          com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.GlobalTypes.DBFileMetaDatas> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.DBFileMetaDatas.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.xtreemfs.babudb.pbrpc.GlobalTypes.DBFileMetaDatas.class,
            org.xtreemfs.babudb.pbrpc.GlobalTypes.DBFileMetaDatas.getDefaultInstance()));
      }
      
      public  void chunk(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.Chunk request,
          com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.xtreemfs.babudb.pbrpc.Common.emptyResponse.class,
            org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance()));
      }
      
      public  void flease(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.FLease request,
          com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(3),
          controller,
          request,
          org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.xtreemfs.babudb.pbrpc.Common.emptyResponse.class,
            org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance()));
      }
      
      public  void localTime(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.Common.emptyRequest request,
          com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.GlobalTypes.Timestamp> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(4),
          controller,
          request,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.Timestamp.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.xtreemfs.babudb.pbrpc.GlobalTypes.Timestamp.class,
            org.xtreemfs.babudb.pbrpc.GlobalTypes.Timestamp.getDefaultInstance()));
      }
      
      public  void replica(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LSNRange request,
          com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.GlobalTypes.LogEntries> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(5),
          controller,
          request,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LogEntries.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.xtreemfs.babudb.pbrpc.GlobalTypes.LogEntries.class,
            org.xtreemfs.babudb.pbrpc.GlobalTypes.LogEntries.getDefaultInstance()));
      }
      
      public  void heartbeat(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN request,
          com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(6),
          controller,
          request,
          org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.xtreemfs.babudb.pbrpc.Common.emptyResponse.class,
            org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance()));
      }
      
      public  void replicate(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN request,
          com.google.protobuf.RpcCallback<org.xtreemfs.babudb.pbrpc.Common.emptyResponse> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(7),
          controller,
          request,
          org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            org.xtreemfs.babudb.pbrpc.Common.emptyResponse.class,
            org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance()));
      }
    }
    
    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }
    
    public interface BlockingInterface {
      public org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN state(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.Common.emptyRequest request)
          throws com.google.protobuf.ServiceException;
      
      public org.xtreemfs.babudb.pbrpc.GlobalTypes.DBFileMetaDatas load(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN request)
          throws com.google.protobuf.ServiceException;
      
      public org.xtreemfs.babudb.pbrpc.Common.emptyResponse chunk(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.Chunk request)
          throws com.google.protobuf.ServiceException;
      
      public org.xtreemfs.babudb.pbrpc.Common.emptyResponse flease(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.FLease request)
          throws com.google.protobuf.ServiceException;
      
      public org.xtreemfs.babudb.pbrpc.GlobalTypes.Timestamp localTime(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.Common.emptyRequest request)
          throws com.google.protobuf.ServiceException;
      
      public org.xtreemfs.babudb.pbrpc.GlobalTypes.LogEntries replica(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LSNRange request)
          throws com.google.protobuf.ServiceException;
      
      public org.xtreemfs.babudb.pbrpc.Common.emptyResponse heartbeat(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN request)
          throws com.google.protobuf.ServiceException;
      
      public org.xtreemfs.babudb.pbrpc.Common.emptyResponse replicate(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN request)
          throws com.google.protobuf.ServiceException;
    }
    
    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }
      
      private final com.google.protobuf.BlockingRpcChannel channel;
      
      public org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN state(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.Common.emptyRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN.getDefaultInstance());
      }
      
      
      public org.xtreemfs.babudb.pbrpc.GlobalTypes.DBFileMetaDatas load(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN request)
          throws com.google.protobuf.ServiceException {
        return (org.xtreemfs.babudb.pbrpc.GlobalTypes.DBFileMetaDatas) channel.callBlockingMethod(
          getDescriptor().getMethods().get(1),
          controller,
          request,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.DBFileMetaDatas.getDefaultInstance());
      }
      
      
      public org.xtreemfs.babudb.pbrpc.Common.emptyResponse chunk(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.Chunk request)
          throws com.google.protobuf.ServiceException {
        return (org.xtreemfs.babudb.pbrpc.Common.emptyResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(2),
          controller,
          request,
          org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance());
      }
      
      
      public org.xtreemfs.babudb.pbrpc.Common.emptyResponse flease(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.FLease request)
          throws com.google.protobuf.ServiceException {
        return (org.xtreemfs.babudb.pbrpc.Common.emptyResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(3),
          controller,
          request,
          org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance());
      }
      
      
      public org.xtreemfs.babudb.pbrpc.GlobalTypes.Timestamp localTime(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.Common.emptyRequest request)
          throws com.google.protobuf.ServiceException {
        return (org.xtreemfs.babudb.pbrpc.GlobalTypes.Timestamp) channel.callBlockingMethod(
          getDescriptor().getMethods().get(4),
          controller,
          request,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.Timestamp.getDefaultInstance());
      }
      
      
      public org.xtreemfs.babudb.pbrpc.GlobalTypes.LogEntries replica(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LSNRange request)
          throws com.google.protobuf.ServiceException {
        return (org.xtreemfs.babudb.pbrpc.GlobalTypes.LogEntries) channel.callBlockingMethod(
          getDescriptor().getMethods().get(5),
          controller,
          request,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LogEntries.getDefaultInstance());
      }
      
      
      public org.xtreemfs.babudb.pbrpc.Common.emptyResponse heartbeat(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN request)
          throws com.google.protobuf.ServiceException {
        return (org.xtreemfs.babudb.pbrpc.Common.emptyResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(6),
          controller,
          request,
          org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance());
      }
      
      
      public org.xtreemfs.babudb.pbrpc.Common.emptyResponse replicate(
          com.google.protobuf.RpcController controller,
          org.xtreemfs.babudb.pbrpc.GlobalTypes.LSN request)
          throws com.google.protobuf.ServiceException {
        return (org.xtreemfs.babudb.pbrpc.Common.emptyResponse) channel.callBlockingMethod(
          getDescriptor().getMethods().get(7),
          controller,
          request,
          org.xtreemfs.babudb.pbrpc.Common.emptyResponse.getDefaultInstance());
      }
      
    }
  }
  
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033interface/replication.proto\022\022org.xtree" +
      "mfs.pbrpc\032\033interface/GlobalTypes.proto\032%" +
      "share/foundation/include/Common.proto\032$s" +
      "hare/foundation/include/PBRPC.proto2\202\001\n\023" +
      "RemoteAccessService\022b\n\016makePersistent\022 ." +
      "org.xtreemfs.pbrpc.emptyRequest\032!.org.xt" +
      "reemfs.pbrpc.emptyResponse\"\013\215\265\030\001\000\000\000\240\265\030\001\032" +
      "\007\225\265\030\021\'\000\0002\270\005\n\022ReplicationService\022K\n\005state" +
      "\022 .org.xtreemfs.pbrpc.emptyRequest\032\027.org" +
      ".xtreemfs.pbrpc.LSN\"\007\215\265\030\001\000\000\000\022M\n\004load\022\027.o",
      "rg.xtreemfs.pbrpc.LSN\032#.org.xtreemfs.pbr" +
      "pc.DBFileMetaDatas\"\007\215\265\030\002\000\000\000\022R\n\005chunk\022\031.o" +
      "rg.xtreemfs.pbrpc.Chunk\032!.org.xtreemfs.p" +
      "brpc.emptyResponse\"\013\215\265\030\003\000\000\000\230\265\030\001\022T\n\006fleas" +
      "e\022\032.org.xtreemfs.pbrpc.FLease\032!.org.xtre" +
      "emfs.pbrpc.emptyResponse\"\013\215\265\030\004\000\000\000\240\265\030\001\022U\n" +
      "\tlocalTime\022 .org.xtreemfs.pbrpc.emptyReq" +
      "uest\032\035.org.xtreemfs.pbrpc.Timestamp\"\007\215\265\030" +
      "\005\000\000\000\022T\n\007replica\022\034.org.xtreemfs.pbrpc.LSN" +
      "Range\032\036.org.xtreemfs.pbrpc.LogEntries\"\013\215",
      "\265\030\006\000\000\000\230\265\030\001\022P\n\theartbeat\022\027.org.xtreemfs.p" +
      "brpc.LSN\032!.org.xtreemfs.pbrpc.emptyRespo" +
      "nse\"\007\215\265\030\007\000\000\000\022T\n\treplicate\022\027.org.xtreemfs" +
      ".pbrpc.LSN\032!.org.xtreemfs.pbrpc.emptyRes" +
      "ponse\"\013\215\265\030\010\000\000\000\240\265\030\001\032\007\225\265\030!N\000\000B\033\n\031org.xtree" +
      "mfs.babudb.pbrpc"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          com.google.protobuf.ExtensionRegistry registry =
            com.google.protobuf.ExtensionRegistry.newInstance();
          registerAllExtensions(registry);
          org.xtreemfs.babudb.pbrpc.GlobalTypes.registerAllExtensions(registry);
          org.xtreemfs.babudb.pbrpc.Common.registerAllExtensions(registry);
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.PBRPC.registerAllExtensions(registry);
          return registry;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.xtreemfs.babudb.pbrpc.GlobalTypes.getDescriptor(),
          org.xtreemfs.babudb.pbrpc.Common.getDescriptor(),
          org.xtreemfs.foundation.pbrpc.generatedinterfaces.PBRPC.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
