module org # 1000
{
  module xtreemfs # 0
  {
    module babudb # 0
    {
      module interfaces # 0
      {
	struct DBFileMetaData # 20 
	{
	  string fileName;
	  uint64_t fileSize;
	  uint32_t maxChunkSize;
	};

	typedef sequence<DBFileMetaData> DBFileMetaDataSet # 30;

	struct LogEntry # 40
	{
	  buffer payload;
	};

	typedef sequence<LogEntry> LogEntries # 50;

	struct LSN # 60
	{
	  uint32_t viewId;
	  uint64_t sequenceNo;
	};

	struct Chunk # 70
	{
	  string fileName;
	  uint64_t begin;
	  uint64_t end;
	};

	struct LSNRange # 80
	{
	  uint32_t viewId;
	  uint64_t sequenceStart;
	  uint64_t sequenceEnd;
	};
      };
    };
  };
};
