module org # 1000
{
  module xtreemfs # 0
  {
    module babudb # 0
    {
      module interfaces # 0
      {
	struct DBFileMetaData # 20 
	{
	  string   fileName;
	  uint64_t fileSize;
	  uint32_t maxChunkSize;
	};

	typedef sequence<DBFileMetaData> DBFileMetaDataSet # 21;

	struct LogEntry # 22
	{
	  buffer payload;
	};

	typedef sequence<LogEntry> LogEntries # 23;

	struct LSN # 24
	{
	  uint32_t viewId;
	  uint64_t sequenceNo;
	};

	struct Chunk # 25
	{
	  string   fileName;
	  uint64_t begin;
	  uint64_t end;
	};

	struct LSNRange # 26
	{
	  uint32_t viewId;
	  uint64_t sequenceStart;
	  uint64_t sequenceEnd;
	};

	struct InetAddress # 27
	{
	  string   address;
	  uint32_t port;
	};
      };
    };
  };
};
